[build]
  command = "npm run build"       # 프로젝트에 맞는 빌드 명령어
  publish = "docs"               # 프론트엔드 빌드 폴더

[functions]
  directory = "netlify/functions" # 함수 폴더 지정
[build.environment]
  NODE_VERSION = "16"

